-- https://www.techonthenet.com/oracle/joins.php

DROP TABLE "SYSTEM"."T_SUPPLIERS";

CREATE TABLE "SYSTEM"."T_SUPPLIERS" 
(	
    "SUPPLIER_ID" NUMBER NOT NULL ENABLE, 
    "SUPPLIER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE
);
   
DROP TABLE "SYSTEM"."T_ORDERS";

CREATE TABLE "SYSTEM"."T_ORDERS" 
(	
    "ORDER_ID" NUMBER NOT NULL ENABLE, 
    "SUPPLIER_ID" NUMBER NOT NULL ENABLE, 
    "ORDER_DATE" DATE, 
    "ORDER_DESC" VARCHAR2(200 BYTE)
);

--------------------------------------------------------------------------------
-- INNER JOIN
--------------------------------------------------------------------------------
REM INSERTING into T_SUPPLIERS
SET DEFINE OFF;
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10000,'IBM');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10001,'HP');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10002,'Microsoft');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10003,'Dell');

REM INSERTING into T_ORDERS
SET DEFINE OFF;
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500125,10000,to_date('01-MAY-18','DD-MON-RR'),'some random description');
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500126,10001,to_date('02-MAY-18','DD-MON-RR'),null);
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500127,10004,to_date('03-MAY-18','DD-MON-RR'),'again some desc');

SELECT 
    T_SUPPLIERS.SUPPLIER_ID, T_SUPPLIERS.SUPPLIER_NAME, T_ORDERS.ORDER_DATE
FROM 
    T_SUPPLIERS INNER JOIN T_ORDERS
    ON T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID;

SELECT
    T_SUPPLIERS.SUPPLIER_ID, T_SUPPLIERS.SUPPLIER_NAME, T_ORDERS.ORDER_DATE
FROM 
    T_SUPPLIERS, T_ORDERS
WHERE 
    T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID;

--------------------------------------------------------------------------------
-- LEFT [OUTER] JOIN
--------------------------------------------------------------------------------
TRUNCATE TABLE T_SUPPLIERS;
TRUNCATE TABLE T_ORDERS;

REM INSERTING into T_SUPPLIERS
SET DEFINE OFF;
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10000,'IBM');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10001,'HP');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10002,'Microsoft');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10003,'Dell');

REM INSERTING into T_ORDERS
SET DEFINE OFF;
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500125,10000,to_date('01-MAY-18','DD-MON-RR'),'some random description');
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500126,10001,to_date('02-MAY-18','DD-MON-RR'),null);

SELECT 
    T_SUPPLIERS.SUPPLIER_ID, T_SUPPLIERS.SUPPLIER_NAME, T_ORDERS.ORDER_DATE
FROM 
    T_SUPPLIERS LEFT OUTER JOIN T_ORDERS
    ON T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID;
    
SELECT 
    T_SUPPLIERS.SUPPLIER_ID, T_SUPPLIERS.SUPPLIER_NAME, T_ORDERS.ORDER_DATE
FROM 
    T_SUPPLIERS, T_ORDERS
WHERE 
    T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID(+);
    
    
--------------------------------------------------------------------------------
-- RIGHT [OUTER] JOIN
--------------------------------------------------------------------------------
TRUNCATE TABLE T_SUPPLIERS;
TRUNCATE TABLE T_ORDERS;

REM INSERTING into T_SUPPLIERS
SET DEFINE OFF;
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10000,'IBM');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10001,'HP');

REM INSERTING into T_ORDERS
SET DEFINE OFF;
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500125,10000,to_date('01-MAY-18','DD-MON-RR'),'some random description');
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500126,10001,to_date('02-MAY-18','DD-MON-RR'),null);
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500127,10002,to_date('03-MAY-18','DD-MON-RR'),'again some desc');

SELECT 
    T_ORDERS.ORDER_ID, T_ORDERS.ORDER_DATE, T_SUPPLIERS.SUPPLIER_NAME
FROM 
    T_SUPPLIERS RIGHT OUTER JOIN T_ORDERS
    ON T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID;
    
SELECT 
     T_ORDERS.ORDER_ID, T_ORDERS.ORDER_DATE, T_SUPPLIERS.SUPPLIER_NAME
FROM 
    T_SUPPLIERS, T_ORDERS
WHERE 
    T_SUPPLIERS.SUPPLIER_ID(+) = T_ORDERS.SUPPLIER_ID;

--------------------------------------------------------------------------------
-- FULL OUTER JOIN
--------------------------------------------------------------------------------
TRUNCATE TABLE T_SUPPLIERS;
TRUNCATE TABLE T_ORDERS;

REM INSERTING into T_SUPPLIERS
SET DEFINE OFF;
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10000,'IBM');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10001,'HP');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10002,'Microsoft');
Insert into T_SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME) values (10003,'Dell');

REM INSERTING into T_ORDERS
SET DEFINE OFF;
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500125,10000,to_date('01-MAY-18','DD-MON-RR'),'some random description');
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500126,10001,to_date('02-MAY-18','DD-MON-RR'),null);
Insert into T_ORDERS (ORDER_ID,SUPPLIER_ID,ORDER_DATE,ORDER_DESC) values (500127,10004,to_date('03-MAY-18','DD-MON-RR'),'again some desc');

SELECT 
    * -- T_SUPPLIERS.SUPPLIER_ID, T_SUPPLIERS.SUPPLIER_NAME, T_ORDERS.ORDER_DATE
FROM 
    T_SUPPLIERS FULL OUTER JOIN T_ORDERS
    ON T_SUPPLIERS.SUPPLIER_ID = T_ORDERS.SUPPLIER_ID;



